version: '3.7'

services:
  quizapp:
    build:
      context: .
    container_name: quizapp
    restart: always
    networks:
      - nginx-proxy-manager_default

networks:
  nginx-proxy-manager_default:
    external: true